name: Upload Python Package

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip poetry
          poetry install --no-dev

      - name: Build and publish
        run: |
          poetry build -n
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
          poetry publish
