name: Python CI

on:
  push:
    paths-ignore:
      - "docs/**"
      - "**.md"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install poetry
        run: |
          python -m pip install --upgrade pip poetry
          poetry config virtualenvs.in-project true

      - name: Cache poetry
        id: cached-poetry-dependencies
        uses: actions/cache@v2
        with:
          # This path is specific to Ubuntu
          path: .venv
          # Look to see if there is a cache hit for the corresponding requirements file
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: |
          poetry install

      - name: Lint with flake8
        run: |
          poetry run flake8 --max-line-length=127

      - name: Type checking with mypy
        run: |
          poetry run mypy censys

      - name: Test with pytest
        run: |
          poetry run pytest
